# Generated by Django 3.2.8 on 2021-11-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211120_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='finches',
            field=models.ManyToManyField(to='main_app.Finch'),
        ),
    ]
