# Generated by Django 3.2.8 on 2021-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_house_finches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='finches',
        ),
        migrations.AddField(
            model_name='finch',
            name='houses',
            field=models.ManyToManyField(to='main_app.House'),
        ),
    ]
